apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8080
<<<<<<< HEAD
      nodePort: 30000
  type: LoadBalancer
=======
  type: LoadBalancer
>>>>>>> fa80460675baebc726ae69a2df442ef7c577c66d
